name: lint

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3.0.0 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.6.2 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false
      - uses: terraform-linters/setup-tflint@v4.0.0 #https://github.com/terraform-linters/setup-tflint/releases
        name: Setup TFLint
        with:
          tflint_version: v0.50.3 # https://github.com/terraform-linters/tflint/releases
      - name: terraform fmt
        run: terraform fmt -recursive -check -diff
      - run: tflint --init
      - run: tflint --recursive --color
